# 1.1

In [18]:
#导入库
import pandas as pd
import numpy as np
import xlwings as xw

In [19]:
#读取数据
data = pd.read_excel(r'C:\Users\Radish\Desktop\data B\附件1.xlsx')
data_city_country = pd.read_excel(r'C:\Users\Radish\Desktop\data B\附件1.xlsx',sheet_name='城市省份对照表')
# data
# data_city_country

In [20]:
#查看表结构
data.dtypes

日期      datetime64[ns]
城市              object
新增确诊             int64
新增治愈             int64
新增死亡             int64
dtype: object

In [21]:
#查看是否有空值
data.isnull().any()
#数据证明没有空值

日期      False
城市      False
新增确诊    False
新增治愈    False
新增死亡    False
dtype: bool

In [22]:
#查看是否有重复值
data.duplicated().any()
#证明没有重复值

False

In [23]:
#Timestamp类型 用to_datetime进行转换
data['日期'] = pd.to_datetime(data['日期'])

In [24]:
#城市 分类
city = data.groupby(by = '城市')
# city.count()

In [25]:
#设置 新建列名
data['累计确诊人数'] = 0
data['累计治愈人数'] = 0
data['累计死亡人数'] = 0

In [26]:
#通过分类和cumsum函数实现累加
data['累计确诊人数'] = city['新增确诊'].apply(lambda x:x.cumsum())
data['累计治愈人数'] = city['新增治愈'].apply(lambda x:x.cumsum())
data['累计死亡人数'] = city['新增死亡'].apply(lambda x:x.cumsum())
data.head()

          日期  城市  新增确诊  新增治愈  新增死亡  累计确诊人数  累计治愈人数  累计死亡人数
0 2020-01-10  武汉    41     2     1      41       2       1
1 2020-01-11  武汉     0     4     0      41       6       1
2 2020-01-12  武汉     0     1     0      41       7       1
3 2020-01-15  武汉     0     5     1      41      12       2
4 2020-01-16  武汉     4     3     0      45      15       2

In [27]:
#保存数据
data1 = data[['城市','日期','累计确诊人数','累计治愈人数','累计死亡人数']]
data1.to_csv(r'C:\Users\Radish\Desktop\data B\task1_1.csv',index=False)

In [28]:
# 建立透视表
pd.pivot_table(data,index=['城市','日期','累计确诊人数','累计治愈人数','累计死亡人数'])

                                      新增死亡  新增治愈  新增确诊
城市   日期         累计确诊人数 累计治愈人数 累计死亡人数
七台河  2020-01-26 1      0      0          0     0     1
     2020-01-27 2      0      0          0     0     1
     2020-01-30 3      0      0          0     0     1
     2020-01-31 5      0      0          0     0     2
     2020-02-01 6      0      0          0     0     1
     2020-02-02 7      0      0          0     0     1
     2020-02-03 8      0      0          0     0     1
     2020-02-04 9      0      0          0     0     1
     2020-02-06 10     0      0          0     0     1
     2020-02-07 11     0      0          0     0     1
     2020-02-08 13     0      0          0     0     2
     2020-02-09 14     0      0          0     0     1
     2020-02-10 15     0      0          0     0     1
     2020-02-12 16     0      0          0     0     1
     2020-02-13 16     1      0          0     1     0
     2020-02-15 16     4      0          0     3     0
     2020-02-17 17     4      0          0     0     1
     2020-02-18 17     6      0          0     2     0
     2020-02-22 17     9      0          0     3     0
     2020-02-23 17     10     0          0     1     0
     2020-02-25 17     11     0          0     1     0
     2020-02-26 17     12     0          0     1     0
     2020-02-27 17     13     0          0     1     0
     2020-03-04 17     14     0          0     1     0
     2020-03-05 17     15     0          0     1     0
     2020-03-06 17     16     0          0     1     0
     2020-03-14 17     17     0          0     1     0
万宁   2020-01-22 1      0      0          0     0     1
     2020-01-23 2      0      0          0     0     1
     2020-01-24 5      0      0          0     0     3
...                                    ...   ...   ...
齐齐哈尔 2020-02-12 33     4      1          0     3     0
     2020-02-13 36     8      1          0     4     3
     2020-02-15 38     8      1          0     0     2
     2020-02-16 42     10     1          0     2     4
     2020-02-17 43     10     1          0     0     1
     2020-02-19 43     11     1          0     1     0
     2020-02-20 43     16     1          0     5     0
     2020-02-21 43     22     1          0     6     0
     2020-02-22 43     23     1          0     1     0
     2020-02-23 43     24     1          0     1     0
     2020-02-24 43     26     1          0     2     0
     2020-02-26 43     28     1          0     2     0
     2020-02-27 43     33     1          0     5     0
     2020-03-02 43     35     1          0     2     0
     2020-03-03 43     36     1          0     1     0
     2020-03-08 43     38     1          0     2     0
     2020-03-09 43     40     1          0     2     0
     2020-03-18 43     41     1          0     1     0
     2020-03-25 43     42     1          0     1     0
龙岩   2020-01-28 1      0      0          0     0     1
     2020-02-03 2      0      0          0     0     1
     2020-02-06 4      0      0          0     0     2
     2020-02-07 5      0      0          0     0     1
     2020-02-08 6      0      0          0     0     1
     2020-02-10 6      1      0          0     1     0
     2020-02-20 6      2      0          0     1     0
     2020-02-21 6      3      0          0     1     0
     2020-02-22 6      4      0          0     1     0
     2020-02-24 6      5      0          0     1     0
     2020-02-26 6      6      0          0     1     0

[10245 rows x 3 columns]

In [29]:
#忽略警告
import warnings
warnings.filterwarnings('ignore')

#先把月份提取出来
data1['月']=data1['日期'].dt.month
data1['日']=data1['日期'].dt.day

In [30]:
#取出武汉、深圳、保定的信息
wuhan = data1.loc[data1.城市 =='武汉']
shenzhen = data1.loc[data1.城市 =='深圳']
baoding = data1.loc[data1.城市 =='保定']

In [31]:
#定义一个函数 作为返回10、25号的累计数据
def sum(city):
    #每月10日的数据
    mon_10 = city.loc[city.日 == 10]

    #每月25日的数据
    mon_25 = city.loc[city.日 == 25]
    
    #返回值
    return mon_10,mon_25

In [32]:
#调用函数
# sum(wuhan)
# sum(shenzhen)
sum(baoding)

(      城市         日期  累计确诊人数  累计治愈人数  累计死亡人数  月   日
 3886  保定 2020-02-10      30       9       0  2  10,
        城市         日期  累计确诊人数  累计治愈人数  累计死亡人数  月   日
 370    保定 2020-01-25       3       0       0  1  25
 10202  保定 2020-06-25      45      33       0  6  25)

# 1.2

In [144]:
#使用匹配机制让两个表相关
df1 = pd.read_csv(r'D:\大数据学习\数据分析与挖掘\20B题\数据\task1_1.csv')
df2=pd.read_excel(r'D:\大数据学习\数据分析与挖掘\20B题\附件1.xlsx','城市省份对照表')

#用merge方法关联两个表
outer=pd.merge(df1,df2,on='城市')

#按省份分类
city = outer.groupby(by='省份')
data1 = outer[['省份','日期','新增确诊','新增治愈','新增死亡','累计确诊人数','累计治愈人数','累计死亡人数']]

# 导出数据
data1.to_csv(r'D:\大数据学习\数据分析与挖掘\20B题\数据\task1_2.csv',index=False)

In [146]:
#导入数据
data1_2=pd.read_csv(r"D:\大数据学习\数据分析与挖掘\20B题\数据\task1_2.csv")

#查看表结构
data1_2.dtypes

省份        object
日期        object
新增确诊       int64
新增治愈       int64
新增死亡       int64
累计确诊人数     int64
累计治愈人数     int64
累计死亡人数     int64
dtype: object

In [147]:
#转化时间格式
data1_2.日期=pd.to_datetime(data1_2.日期,format='%Y/%m/%d')

In [150]:
#提取 日、月的数据
data1_2['月']=data1_2['日期'].dt.month
data1_2['日']=data1_2['日期'].dt.day

#查看表
data1_2

       省份         日期  新增确诊  新增治愈  新增死亡  累计确诊人数  累计治愈人数  累计死亡人数  月   日
0      湖北 2020-01-10    41     2     1      41       2       1  1  10
1      湖北 2020-01-11     0     4     0      41       6       1  1  11
2      湖北 2020-01-12     0     1     0      41       7       1  1  12
3      湖北 2020-01-15     0     5     1      41      12       2  1  15
4      湖北 2020-01-16     4     3     0      45      15       2  1  16
...    ..        ...   ...   ...   ...     ...     ...     ... ..  ..
10240  湖南 2020-04-17     0     1     0       1       1       0  4  17
10241  安徽 2020-04-08     1     0     0       1       0       0  4   8
10242  安徽 2020-04-24     0     1     0       1       1       0  4  24
10243  辽宁 2020-04-16     1     0     0       1       0       0  4  16
10244  辽宁 2020-05-01     0     1     0       1       1       0  5   1

[10245 rows x 10 columns]

In [151]:
#提取省份为湖北的每月15号的数据
data1_2_1=data1_2.loc[data1_2['省份']=='湖北']
data1_2_2=data1_2_1.loc[data1_2_1['日']==15]

#查看表
data1_2_2

      省份         日期  新增确诊  新增治愈  新增死亡  累计确诊人数  累计治愈人数  累计死亡人数  月   日
3     湖北 2020-01-15     0     5     1      41      12       2  1  15
34    湖北 2020-02-15  1548   413   110   39462    3151    1233  2  15
63    湖北 2020-03-15     4   752    13   50003   38537    2469  3  15
94    湖北 2020-04-15     0    33     0   50008   46325    2579  4  15
298   湖北 2020-02-15     6   105     7    2823     718      75  2  15
327   湖北 2020-03-15     0    12     0    2907    2750     125  3  15
2197  湖北 2020-02-15     3     5     2     904     117      30  2  15
2226  湖北 2020-03-15     0     1     0     928     865      39  3  15
2262  湖北 2020-02-15    12    71     4    1490     263      36  2  15
2291  湖北 2020-03-15     0     9     0    1580    1492      50  3  15
4081  湖北 2020-02-15     5    16     0     602     116       2  2  15
4110  湖北 2020-03-15     0     4     0     672     634       8  3  15
4331  湖北 2020-02-15     9    24     0     523      87      17  2  15
4357  湖北 2020-03-15     0     3     0     575     529      22  3  15
4424  湖北 2020-02-15    87    40     3    3201     353      65  2  15
4453  湖北 2020-03-15     0    13     1    3518    3266     127  3  15
4631  湖北 2020-02-15     0    48     6     895     140      21  2  15
4660  湖北 2020-03-15     0     4     0     931     868      36  3  15
5143  湖北 2020-02-15    38    23     1    1230     222      34  2  15
5172  湖北 2020-03-15     0     3     0    1394    1275      57  3  15
5208  湖北 2020-02-15     3     5     0     247      76       4  2  15
5234  湖北 2020-03-15     0     1     0     252     242       7  3  15
5828  湖北 2020-02-15    22    17     3    1254     113      22  2  15
5857  湖北 2020-03-15     0     8     0    1307    1221      45  3  15
5889  湖北 2020-02-15    25     6     0     447      27      10  2  15
6702  湖北 2020-02-15     3    22     1     983     192      14  2  15
6731  湖北 2020-03-15     0     2     0    1015     950      38  3  15
7117  湖北 2020-02-15    12    25     0     816     152       8  2  15
7180  湖北 2020-02-15    16    29     1    1144     113      19  2  15
7209  湖北 2020-03-15     0     3     0    1175    1128      38  3  15
7713  湖北 2020-02-15    50     0     1     166      12       6  2  15
7740  湖北 2020-03-15     0     1     0     198     183       9  3  15

In [152]:
#提取省份为广东的每月15号的数据
data1_2_3=data1_2.loc[data1_2['省份']=='广东']
data1_2_4=data1_2_3.loc[data1_2_3['日']==15]

#查看表
data1_2_4

      省份         日期  新增确诊  新增治愈  新增死亡  累计确诊人数  累计治愈人数  累计死亡人数  月   日
176   广东 2020-02-15     8    11     0     414     115       0  2  15
200   广东 2020-03-15     0     5     0     417     401       3  3  15
353   广东 2020-02-15     0     8     0      58      26       0  2  15
583   广东 2020-02-15     1     3     0      96      37       0  2  15
754   广东 2020-02-15     0     1     0      84      23       0  2  15
770   广东 2020-04-15     1     0     0      87      80       0  4  15
867   广东 2020-02-15     3    15     0     338     121       0  2  15
903   广东 2020-04-15     4     0     0     371     330       1  4  15
1167  广东 2020-02-15     0     1     0      10       4       0  2  15
3183  广东 2020-02-15     0     1     0      17       8       1  2  15
3210  广东 2020-02-15     0     3     0      65      33       0  2  15
4603  广东 2020-02-15     0     2     0      13       7       0  2  15
5101  广东 2020-02-15     8     2     0      89      12       1  2  15
5696  广东 2020-02-15     0     2     0      25      11       0  2  15
7564  广东 2020-02-15     1     0     0      16       7       0  2  15
8937  广东 2020-02-15     1     0     0      23       3       0  2  15
9134  广东 2020-02-15     0     1     0       5       1       0  2  15
9520  广东 2020-03-15     4     0     0      11       0       0  3  15
9569  广东 2020-06-15     3     0     0     233      88       0  6  15

In [153]:
##提取省份为河北的每月15号的数据
data1_2_5=data1_2.loc[data1_2['省份']=='河北']
data1_2_6=data1_2_5.loc[data1_2_5['日']==15]

#查看表
data1_2_6

       省份         日期  新增确诊  新增治愈  新增死亡  累计确诊人数  累计治愈人数  累计死亡人数  月   日
2755   河北 2020-02-15     1     0     0      28       7       0  2  15
3345   河北 2020-02-15     1     0     0      47      14       2  2  15
4888   河北 2020-02-15     0     2     0      32      19       0  2  15
4894   河北 2020-06-15     4     0     0      36      32       0  6  15
7493   河北 2020-02-15     1     2     0      30      14       0  2  15
7932   河北 2020-02-15     0     2     0      22      10       1  2  15
8486   河北 2020-02-15     5     5     0      51       9       0  2  15
8850   河北 2020-02-15     1     2     0      34       9       0  2  15
9202   河北 2020-02-15     0     1     0      10       3       0  2  15
10078  河北 2020-04-15     1     1     0      10       4       0  4  15

In [154]:
#链接三个分析表 形成透视图 更加直观
data1_2_t=pd.concat([data1_2_2,data1_2_4,data1_2_6])
data1_2_t1=data1_2_t.groupby(by=['省份','日期'])   #按省份和日期分类
data1_2_t2=data1_2_t1.aggregate({'累计确诊人数':np.sum,'累计治愈人数':np.sum,'累计死亡人数':np.sum})  #通过np算出数据
data1_2_t2

               累计确诊人数  累计治愈人数  累计死亡人数
省份 日期
广东 2020-02-15    1253     408       2
   2020-03-15     428     401       3
   2020-04-15     458     410       1
   2020-06-15     233      88       0
河北 2020-02-15     254      85       3
   2020-04-15      10       4       0
   2020-06-15      36      32       0
湖北 2020-01-15      41      12       2
   2020-02-15   56187    5852    1596
   2020-03-15   66455   53940    3070
   2020-04-15   50008   46325    2579

# 1.3

In [155]:
#导入数据
data1_3=pd.read_csv(r'D:\大数据学习\数据分析与挖掘\20B题\数据\task1_2.csv')
data1_3

       省份          日期  新增确诊  新增治愈  新增死亡  累计确诊人数  累计治愈人数  累计死亡人数
0      湖北  2020-01-10    41     2     1      41       2       1
1      湖北  2020-01-11     0     4     0      41       6       1
2      湖北  2020-01-12     0     1     0      41       7       1
3      湖北  2020-01-15     0     5     1      41      12       2
4      湖北  2020-01-16     4     3     0      45      15       2
...    ..         ...   ...   ...   ...     ...     ...     ...
10240  湖南  2020-04-17     0     1     0       1       1       0
10241  安徽  2020-04-08     1     0     0       1       0       0
10242  安徽  2020-04-24     0     1     0       1       1       0
10243  辽宁  2020-04-16     1     0     0       1       0       0
10244  辽宁  2020-05-01     0     1     0       1       1       0

[10245 rows x 8 columns]

In [156]:
#计算住院人数
data1_3['住院人数']=data1_3['累计确诊人数']-data1_3['累计治愈人数']-data1_3['累计死亡人数']
data1_3

       省份          日期  新增确诊  新增治愈  新增死亡  累计确诊人数  累计治愈人数  累计死亡人数  住院人数
0      湖北  2020-01-10    41     2     1      41       2       1    38
1      湖北  2020-01-11     0     4     0      41       6       1    34
2      湖北  2020-01-12     0     1     0      41       7       1    33
3      湖北  2020-01-15     0     5     1      41      12       2    27
4      湖北  2020-01-16     4     3     0      45      15       2    28
...    ..         ...   ...   ...   ...     ...     ...     ...   ...
10240  湖南  2020-04-17     0     1     0       1       1       0     0
10241  安徽  2020-04-08     1     0     0       1       0       0     1
10242  安徽  2020-04-24     0     1     0       1       1       0     0
10243  辽宁  2020-04-16     1     0     0       1       0       0     1
10244  辽宁  2020-05-01     0     1     0       1       1       0     0

[10245 rows x 9 columns]

In [157]:
#建立透视表
data1_3_1=data1_3[['省份','日期','住院人数']]
#到处task1_3.csv
data1_3_1.to_csv(r'D:\大数据学习\数据分析与挖掘\20B题\数据\task1_3.csv')

In [158]:
data1_3_1

       省份          日期  住院人数
0      湖北  2020-01-10    38
1      湖北  2020-01-11    34
2      湖北  2020-01-12    33
3      湖北  2020-01-15    27
4      湖北  2020-01-16    28
...    ..         ...   ...
10240  湖南  2020-04-17     0
10241  安徽  2020-04-08     1
10242  安徽  2020-04-24     0
10243  辽宁  2020-04-16     1
10244  辽宁  2020-05-01     0

[10245 rows x 3 columns]

In [159]:
#忽略警告
import warnings
warnings.filterwarnings('ignore')

#修改日期格式
data1_3_1.日期=pd.to_datetime(data1_3_1.日期,format='%Y/%m/%d')

#提取 月、日 的数据
data1_3_1['月']=data1_3_1['日期'].dt.month
data1_3_1['日']=data1_3_1['日期'].dt.day
data1_3_1

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py:5303: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

       省份         日期  住院人数  月   日
0      湖北 2020-01-10    38  1  10
1      湖北 2020-01-11    34  1  11
2      湖北 2020-01-12    33  1  12
3      湖北 2020-01-15    27  1  15
4      湖北 2020-01-16    28  1  16
...    ..        ...   ... ..  ..
10240  湖南 2020-04-17     0  4  17
10241  安徽 2020-04-08     1  4   8
10242  安徽 2020-04-24     0  4  24
10243  辽宁 2020-04-16     1  4  16
10244  辽宁 2020-05-01     0  5   1

[10245 rows x 5 columns]

In [1]:
#提取湖北省各地每月20号的住院人数
data1_3_2=data1_3_1.loc[data1_3_1['省份']=='湖北']
data1_3_3=data1_3_2.loc[data1_3_1['日']==20]
data1_3_3.heaad()

NameError: name 'data1_3_1' is not defined

In [161]:
#提取广东省各地每月20号的住院人数
data1_3_4=data1_3_1.loc[data1_3_1['省份']=='广东']
data1_3_5=data1_3_4.loc[data1_3_1['日']==20]
data1_3_5

      省份         日期  住院人数  月   日
150   广东 2020-01-20     9  1  20
181   广东 2020-02-20   215  2  20
203   广东 2020-03-20     4  3  20
331   广东 2020-01-20     1  1  20
357   广东 2020-02-20    21  2  20
525   广东 2020-01-20     1  1  20
542   广东 2020-02-20    10  2  20
561   广东 2020-01-20     3  1  20
587   广东 2020-02-20    48  2  20
771   广东 2020-04-20     8  4  20
872   广东 2020-02-20   167  2  20
3215  广东 2020-02-20    23  2  20
4605  广东 2020-02-20     3  2  20
5106  广东 2020-02-20    65  2  20
5701  广东 2020-02-20     5  2  20
9525  广东 2020-03-20    48  3  20
9555  广东 2020-05-20   110  5  20

In [162]:
#提取上海市各地每月20号的住院人数
data1_3_6=data1_3_1.loc[data1_3_1['省份']=='上海']
data1_3_7=data1_3_6.loc[data1_3_1['日']==20]
data1_3_7

      省份         日期  住院人数  月   日
416   上海 2020-01-20     1  1  20
443   上海 2020-02-20    41  2  20
461   上海 2020-05-20     7  5  20
8105  上海 2020-02-20    12  2  20
8274  上海 2020-02-20     3  2  20
8288  上海 2020-02-20     6  2  20
8349  上海 2020-02-20     4  2  20
8396  上海 2020-02-20    22  2  20
8559  上海 2020-02-20     9  2  20
8626  上海 2020-02-20     3  2  20
9187  上海 2020-02-20     5  2  20
9665  上海 2020-03-20    41  3  20
9696  上海 2020-04-20   100  4  20
9722  上海 2020-05-20    13  5  20

In [163]:
#连接三个表 创建透视表 展示各地区每个月20号前的住院人数
data1_3_t=pd.concat([data1_3_3,data1_3_5,data1_3_7])
data1_3_t1=data1_3_t.groupby(by=['省份','日期'])
data1_3_t2=data1_3_t1.aggregate({'住院人数':np.sum})
data1_3_t2

                住院人数
省份 日期
上海 2020-01-20      1
   2020-02-20    105
   2020-03-20     41
   2020-04-20    100
   2020-05-20     20
广东 2020-01-20     14
   2020-02-20    557
   2020-03-20     52
   2020-04-20      8
   2020-05-20    110
湖北 2020-01-20    239
   2020-02-20  48725
   2020-03-20   5595
   2020-04-20    102